Import("context", "env")
import addons

addon_env = env.Clone()

source = ["color.c"]

result = addons.do_build(
   context = context,
   env = addon_env,
   source = source,
   dir = "color",
   name = "a5_color",
   install_headers = ["allegro5/a5_color.h"])

Return("result")
