Import("context")
import addons

addons.do_build(
    context = context,
    source = ["bmp.c", "iio.c", "pcx.c", "tga.c"],
    dir = 'iio',
    name = 'a5_iio',
    install_headers = ['allegro5/a5_iio.h']
)

x = True
Return("x")
