Import("context")
Import("env")
import addons, helpers
import os

def getArgumentOption(name, default):
    arg = ARGUMENTS.get(name,default)
    if arg == "yes" or arg == "1":
        return 1
    return 0

myEnv = env.Clone()

tests = {}

def setupPlatform(settings, config):
    settings["ALLEGRO_CFG_IIO_HAVE_PNG"] = config.CheckHeader("png.h") and\
            config.CheckLib("png")
    return config.Finish()

settings, configure_env = helpers.do_configure('iio', context,
                            tests, setupPlatform,
                            'allegro5/internal/aintern_iio_cfg.h.cmake',
                            'allegro5/internal/aintern_iio_cfg.h',
                            getArgumentOption('config', 0))


env.Append(LIBS = ['png','z'])

addons.do_build(
    context = context,
    env = myEnv,
    source = ["bmp.c", "iio.c", "pcx.c", "tga.c", "png.c"],
    libs = ["png", "z"],
    dir = "iio",
    name = "a5_iio",
    install_headers = ["allegro5/a5_iio.h",
    "allegro5/internal/aintern_iio_cfg.h"]
)

x = True
Return("x")
