#ifndef __DEMODATA_H__
#define __DEMODATA_H__

enum {
   DEMO_BMP_BACK,
   DEMO_FONT,
   DEMO_FONT_LOGO,
   DEMO_MIDI_INGAME,
   DEMO_MIDI_INTRO,
   DEMO_MIDI_MENU,
   DEMO_MIDI_SUCCESS,
   DEMO_SAMPLE_BUTTON,
   DEMO_SAMPLE_WELCOME,
   DEMO_SAMPLE_SKATING,
   DEMO_SAMPLE_WAVE,
   DEMO_SAMPLE_DING,
   DEMO_SAMPLE_DOOROPEN,
   DEMO_SAMPLE_POP,

   DEMO_BMP_BANANAS,
   DEMO_BMP_CHERRIES,
   DEMO_BMP_CLOUD,
   DEMO_BMP_DOOROPEN,
   DEMO_BMP_DOORSHUT,
   DEMO_BMP_EXITSIGN,
   DEMO_BMP_GRASS,
   DEMO_BMP_ICECREAM,
   DEMO_BMP_ICE,
   DEMO_BMP_ICETIP,
   DEMO_BMP_ORANGE,
   DEMO_BMP_SKATEFAST,
   DEMO_BMP_SKATEMED,
   DEMO_BMP_SKATER1,
   DEMO_BMP_SKATER2,
   DEMO_BMP_SKATER3,
   DEMO_BMP_SKATER4,
   DEMO_BMP_SKATESLOW,
   DEMO_BMP_SOIL,
   DEMO_BMP_SWEET,
   DEMO_BMP_WATER,

   DEMO_DATA_COUNT
};

#endif
