@echo off
rem
rem  Sets up the Allegro package for building with Borland C++Builder.
rem  Simply writes a new makefile to point to BCC32-specific stuff.
rem

echo Configuring Allegro for Windows (BCC32)...

echo # generated by fixbcc32.bat > makefile
echo MAKEFILE_INC = makefile.bcc >> makefile
echo include makefile.all >> makefile

echo /* generated by fixbcc32.bat */ > include\allegro\alplatf.h
echo #define ALLEGRO_BCC32 >> include\allegro\alplatf.h

echo Done!
