@echo off
rem
rem  Sets up the Allegro package for building with djgpp, generating the
rem  makefile.inc stub and converting text files from LF to CR/LF format.
rem

echo Converting Allegro files to DOS (djgpp) format...

echo # generated by fixdjgpp.bat > makefile
echo MAKEFILE_INC = makefile.dj >> makefile
echo include makefile.all >> makefile

echo /* generated by fixdjgpp.bat */ > include\allegro\alplatf.h
echo #include "aldjgpp.h" >> include\allegro\alplatf.h

utod *.bat .../*.c *.cfg .../*.h .../*.inc
utod .../*.s .../*.txt .../*._tx makefile.* readme.*

echo Done!
