@echo off
rem
rem  Sets up the Allegro package for building with djgpp, generating the
rem  makefile.inc stub and converting text files from LF to CR/LF format.
rem

echo Configuring Allegro for DOS (djgpp)...

echo # generated by fixdjgpp.bat > makefile
echo MAKEFILE_INC = makefile.dj >> makefile
echo include makefile.all >> makefile

echo /* generated by fixdjgpp.bat */ > include\allegro\alplatf.h
echo #define ALLEGRO_DJGPP >> include\allegro\alplatf.h

if [%1] == [--quick] goto done
echo Converting Allegro files to DOS (djgpp) format...
utod *.bat .../*.c *.cfg .../*.h .../*.inc
utod .../*.s .../*.txt .../*._tx makefile.* readme.*
:done

echo Done!
