@echo off
rem
rem  Sets up the Allegro package for building with MSVC, generating the
rem  makefile.inc stub and converting text files from LF to CR/LF format.
rem

echo Converting Allegro files to Windows (MSVC) format...

echo # generated by fixmsvc.bat > makefile
echo MAKEFILE_INC = makefile.vc >> makefile
echo include makefile.all >> makefile

utod *.bat .../*.c *.cfg .../*.h .../*.inc .../*.rc
utod .../*.s .../*.txt .../*._tx makefile.* readme.*

echo Done!
