@echo off
rem
rem  Sets up the Allegro package for building with Mingw32.
rem

echo Configuring Allegro for Windows (Mingw32)...

echo # generated by fixming.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile

echo /* generated by fixming.bat */ > include\allegro\alplatf.h
echo #define ALLEGRO_MINGW32 >> include\allegro\alplatf.h

echo Done!
