@echo off
rem
rem  Sets up the Allegro package for building with Mingw32.
rem

echo Converting Allegro files to Windows (Mingw32) format...

echo # generated by fixming.bat > makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo include makefile.all >> makefile

echo Done!
