@echo off
rem
rem  Sets up the Allegro package for building with MSVC, generating the
rem  makefile.inc stub and converting text files from LF to CR/LF format.
rem

echo Configuring Allegro for Windows (MSVC)...

echo # generated by fixmsvc.bat > makefile
echo MAKEFILE_INC = makefile.vc >> makefile
echo include makefile.all >> makefile

echo /* generated by fixmsvc.bat */ > include\allegro\alplatf.h
echo #define ALLEGRO_MSVC >> include\allegro\alplatf.h

if [%1] == [--quick] goto done
echo Converting Allegro files to Windows (MSVC) format...
utod *.bat .../*.c *.cfg .../*.h .../*.inc .../*.rc
utod .../*.s .../*.txt .../*._tx makefile.* readme.*
:done

echo Done!

