@echo off
rem
rem  Sets up the Allegro package for building with Mingw32.
rem

echo Converting Allegro files to Windows (Mingw32) format...

echo # generated by fixming.bat > makefile
echo ifdef STATICLINK >> makefile
echo MAKEFILE_INC = makefile.mgs >> makefile
echo else >> makefile
echo MAKEFILE_INC = makefile.mgw >> makefile
echo endif >> makefile
echo include makefile.all >> makefile

echo.
echo Note: this is not a full Mingw32 port of the Allegro library.
echo.
echo DLL version:
echo This makefile will create an import library and build all the
echo test programs using Mingw32, but the library code lives in
echo a DLL that is built with MSVC. If you haven't already got
echo the DLL, run "fixmsvc" and then "make install" to build it.
echo.
echo Static link version:
echo This one doesn't need MSVC, consult the readme file for
echo additional info...
