@echo off
rem
rem  Sets up the Allegro package for building with RSXNT.
rem

echo Converting Allegro files to Windows (RSXNT) format...

echo # generated by fixrsxnt.bat > makefile
echo MAKEFILE_INC = makefile.rsx >> makefile
echo include makefile.all >> makefile

echo.
echo Note: this is not a full RSXNT port of the Allegro library. This makefile
echo will create an import library and build all the test programs using RSXNT,
echo but the library code lives in a DLL that is built with MSVC. If you haven't
echo already got the DLL, run "fixmsvc" and then "make install" to build it.
echo Also, the RSXNT makefile doesn't bother to convert the documentation or to
echo copy headers into the djgpp include directory. If you want that, "fixdjgpp"
echo and then "make install" will do it for you.
