
# DLL filename number for Windows
LIBRARY_VERSION = 49

# Shared library versions for Unix
shared_version = 4.9.2
shared_major_minor = 4.9

# Compatibility version for Mac OS X
compatibility_version = 4.9.0
