# a big bad list of all the library source files

ALLEGRO_SRC_FILES = \
	src/allegro.c \
	src/blit.c \
	src/bmp.c \
	src/clip3d.c \
	src/clip3df.c \
	src/colblend.c \
	src/color.c \
	src/config.c \
	src/datafile.c \
	src/dataregi.c \
	src/digmid.c \
	src/dither.c \
	src/dispsw.c \
	src/drvlist.c \
	src/file.c \
	src/fli.c \
	src/flood.c \
	src/font.c \
	src/fontbios.c \
	src/fontbmp.c \
	src/fontdat.c \
	src/fontgrx.c \
	src/fonttxt.c \
	src/fsel.c \
	src/gfx.c \
	src/glyph.c \
	src/graphics.c \
	src/gsprite.c \
	src/gui.c \
	src/guiproc.c \
	src/inline.c \
	src/joystick.c \
	src/keyboard.c \
	src/lbm.c \
	src/libc.c \
	src/lzss.c \
	src/math.c \
	src/math3d.c \
	src/midi.c \
	src/mixer.c \
	src/modesel.c \
	src/mouse.c \
	src/pcx.c \
	src/poly3d.c \
	src/polygon.c \
	src/quantize.c \
	src/quat.c \
	src/readbmp.c \
	src/readfont.c \
	src/readsmp.c \
	src/rle.c \
	src/rotate.c \
	src/scene3d.c \
	src/sound.c \
	src/spline.c \
	src/stream.c \
	src/text.c \
	src/tga.c \
	src/timer.c \
	src/unicode.c \
	src/vtable.c \
	src/vtable15.c \
	src/vtable16.c \
	src/vtable24.c \
	src/vtable32.c \
	src/vtable8.c

ALLEGRO_SRC_C_FILES = \
	src/c/cblit16.c \
	src/c/cblit24.c \
	src/c/cblit32.c \
	src/c/cblit8.c \
	src/c/ccpu.c \
	src/c/ccsprite.c \
	src/c/cgfx15.c \
	src/c/cgfx16.c \
	src/c/cgfx24.c \
	src/c/cgfx32.c \
	src/c/cgfx8.c \
	src/c/cmisc.c \
	src/c/cscan15.c \
	src/c/cscan16.c \
	src/c/cscan24.c \
	src/c/cscan32.c \
	src/c/cscan8.c \
	src/c/cspr15.c \
	src/c/cspr16.c \
	src/c/cspr24.c \
	src/c/cspr32.c \
	src/c/cspr8.c \
	src/c/cstretch.c \
	src/c/czscan15.c \
	src/c/czscan16.c \
	src/c/czscan24.c \
	src/c/czscan32.c \
	src/c/czscan8.c \
	src/misc/ccolconv.c

ALLEGRO_SRC_I386_FILES = \
	src/i386/iblit16.s \
	src/i386/iblit24.s \
	src/i386/iblit32.s \
	src/i386/iblit8.s \
	src/i386/icpu.c \
	src/i386/icpus.s \
	src/i386/icsprite.c \
	src/i386/igfx15.s \
	src/i386/igfx16.s \
	src/i386/igfx24.s \
	src/i386/igfx32.s \
	src/i386/igfx8.s \
	src/i386/imisc.s \
	src/i386/iscan.s \
	src/i386/iscanmmx.s \
	src/i386/ispr15.s \
	src/i386/ispr16.s \
	src/i386/ispr24.s \
	src/i386/ispr32.s \
	src/i386/ispr8.s \
	src/i386/istretch.c \
	src/i386/izbuf.s \
	src/misc/icolconv.s

ALLEGRO_SRC_AMD64_FILES = \
	src/c/cblit16.c \
	src/c/cblit24.c \
	src/c/cblit32.c \
	src/c/cblit8.c \
	src/i386/icpu.c \
	src/amd64/acpus.s \
	src/c/ccsprite.c \
	src/c/cgfx15.c \
	src/c/cgfx16.c \
	src/c/cgfx24.c \
	src/c/cgfx32.c \
	src/c/cgfx8.c \
	src/c/cmisc.c \
	src/c/cscan15.c \
	src/c/cscan16.c \
	src/c/cscan24.c \
	src/c/cscan32.c \
	src/c/cscan8.c \
	src/c/cspr15.c \
	src/c/cspr16.c \
	src/c/cspr24.c \
	src/c/cspr32.c \
	src/c/cspr8.c \
	src/c/cstretch.c \
	src/c/czscan15.c \
	src/c/czscan16.c \
	src/c/czscan24.c \
	src/c/czscan32.c \
	src/c/czscan8.c \
	src/misc/ccolconv.c

ALLEGRO_SRC_DOS_FILES = \
	src/dos/adlib.c \
	src/dos/awedata.c \
	src/dos/dfile.c \
	src/dos/dgfxdrv.c \
	src/dos/djoydrv.c \
	src/dos/dkeybd.c \
	src/dos/dma.c \
	src/dos/dmouse.c \
	src/dos/dpmi.c \
	src/dos/dsnddrv.c \
	src/dos/dsystem.c \
	src/dos/dtimer.c \
	src/dos/emu8k.c \
	src/dos/emu8kmid.c \
	src/dos/essaudio.c \
	src/dos/gpro.c \
	src/dos/grip.c \
	src/dos/gripjoy.c \
	src/dos/gripfnc.s \
	src/dos/ifsega.c \
	src/dos/ifsega2f.c \
	src/dos/ifsega2p.c \
	src/dos/joystd.c \
	src/dos/mpu.c \
	src/dos/multijoy.c \
	src/dos/n64pad.c \
	src/dos/pic.c \
	src/dos/psxpad.c \
	src/dos/sb.c \
	src/dos/sndscape.c \
	src/dos/snespad.c \
	src/dos/sw.c \
	src/dos/swpp.c \
	src/dos/swpps.s \
	src/dos/vesa.c \
	src/dos/vesas.s \
	src/dos/wss.c \
	src/dos/ww.c \
	src/misc/modex.c \
	src/misc/modexgfx.s \
	src/misc/modexsms.c \
	src/misc/pckeys.c \
	src/misc/vbeaf.c \
	src/misc/vbeafs.s \
	src/misc/vbeafex.c \
	src/misc/vga.c \
	src/misc/vgaregs.c

ALLEGRO_SRC_WIN_FILES = \
	src/win/asmlock.s \
	src/win/dllver.rc \
	src/win/gdi.c \
	src/win/wddaccel.c \
	src/win/wddbmp.c \
	src/win/wddbmpl.c \
	src/win/wddraw.c \
	src/win/wddfull.c \
	src/win/wddlock.c \
	src/win/wddmode.c \
	src/win/wddovl.c \
	src/win/wddwin.c \
	src/win/wdsinput.c \
	src/win/wdsndmix.c \
	src/win/wdsound.c \
	src/win/wsndwo.c \
	src/win/wdxver.c \
	src/win/wdispsw.c \
	src/win/wfile.c \
	src/win/wgdi.c \
	src/win/wgfxdrv.c \
	src/win/winput.c \
	src/win/wjoydrv.c \
	src/win/wjoydx.c \
	src/win/wjoyhelp.c \
	src/win/wjoyw32.c \
	src/win/wkeybd.c \
	src/win/wmidi.c \
	src/win/wmouse.c \
	src/win/wsnddrv.c \
	src/win/wsystem.c \
	src/win/wthread.c \
	src/win/wtimer.c \
	src/win/wwnd.c \
	src/misc/colconv.c

ALLEGRO_SRC_BEOS_FILES = \
	src/beos/baccel.cpp \
	src/beos/bdispsw.cpp \
	src/beos/bdwindow.cpp \
	src/beos/bgfx.c \
	src/beos/bgfxapi.cpp \
	src/beos/bgfxdrv.c \
	src/beos/bjoy.c \
	src/beos/bjoydrv.c \
	src/beos/bjoyapi.cpp \
	src/beos/bkey.c \
	src/beos/bkeyapi.cpp \
	src/beos/bkeydrv.c \
	src/beos/bmidi.c \
	src/beos/bmidiapi.cpp \
	src/beos/bmididrv.c \
	src/beos/bmousapi.cpp \
	src/beos/bmousdrv.c \
	src/beos/bmouse.c \
	src/beos/boverlay.c \
	src/beos/bsnd.c \
	src/beos/bsndapi.cpp \
	src/beos/bsnddrv.c \
	src/beos/bswitch.s \
	src/beos/bsysapi.cpp \
	src/beos/bsysdrv.c \
	src/beos/bsystem.c \
	src/beos/btimeapi.cpp \
	src/beos/btimedrv.c \
	src/beos/btimer.c \
	src/beos/bwindow.c \
	src/beos/bwscreen.cpp \
	src/unix/ufile.c \
	src/misc/colconv.c \
	src/misc/pckeys.c

ALLEGRO_SRC_LINUX_FILES = \
	src/linux/fbcon.c \
	src/linux/lconsole.c \
	src/linux/lgfxdrv.c \
	src/linux/ljoy.c \
	src/linux/lkeybd.c \
	src/linux/lmemory.c \
	src/linux/lmouse.c \
	src/linux/lmsedrv.c \
	src/linux/lmsegpmd.c \
	src/linux/lmsems.c \
	src/linux/lmseps2.c \
	src/linux/lmseev.c \
	src/linux/lstddrv.c \
	src/linux/lsystem.c \
	src/linux/ltimer.c \
	src/linux/lvga.c \
	src/linux/lvgahelp.c \
	src/linux/svgalib.c \
	src/linux/svgalibs.s \
	src/linux/vtswitch.c \
	src/misc/vbeaf.c \
	src/misc/vbeafs.s \
	src/misc/vgaregs.c \
	src/misc/vga.c \
	src/misc/modex.c \
	src/misc/modexgfx.s

ALLEGRO_SRC_UNIX_FILES = \
	src/unix/alsa5.c \
	src/unix/alsa9.c \
	src/unix/alsamidi.c \
	src/unix/arts.c \
	src/unix/sgial.c \
	src/unix/jack.c \
	src/unix/udjgpp.c \
	src/unix/udrvlist.c \
	src/unix/udummy.c \
	src/unix/uesd.c \
	src/unix/ufile.c \
	src/unix/ugfxdrv.c \
	src/unix/ujoydrv.c \
	src/unix/ukeybd.c \
	src/unix/umain.c \
	src/unix/umodules.c \
	src/unix/umouse.c \
	src/unix/uoss.c \
	src/unix/uossmidi.c \
	src/unix/uptimer.c \
	src/unix/usigalrm.c \
	src/unix/usnddrv.c \
	src/unix/ustimer.c \
	src/unix/usystem.c \
	src/unix/uthreads.c \
	src/unix/utimer.c \
	src/misc/modexsms.c

ALLEGRO_SRC_X_FILES = \
	src/x/xgfxdrv.c \
	src/x/xkeyboard.c \
	src/x/xmouse.c \
	src/x/xsystem.c \
	src/x/xtimer.c \
	src/x/xvtable.c \
	src/x/xwin.c \
	src/x/xdga2.c \
	src/x/xdga2s.s \
	src/x/xwins.s \
	src/misc/colconv.c
	
ALLEGRO_SRC_QNX_FILES = \
	src/qnx/qdrivers.c \
	src/qnx/qkeydrv.c \
	src/qnx/qmouse.c \
	src/qnx/qphaccel.c \
	src/qnx/qphbmp.c \
	src/qnx/qphfull.c \
	src/qnx/qphoton.c \
	src/qnx/qphwin.c \
	src/qnx/qswitch.s \
	src/qnx/qsystem.c \
	src/unix/alsa5.c \
	src/unix/alsamidi.c \
	src/unix/udjgpp.c \
	src/unix/ufile.c \
	src/unix/umain.c \
	src/unix/uptimer.c \
	src/unix/usystem.c \
	src/unix/uthreads.c \
	src/unix/utimer.c \
	src/misc/colconv.c \
	src/misc/pckeys.c

ALLEGRO_SRC_MACOSX_FILES = \
	src/macosx/cadigi.m \
	src/macosx/camidi.m \
	src/macosx/drivers.m \
	src/macosx/hidjoy.m \
	src/macosx/hidman.m \
	src/macosx/keybd.m \
	src/macosx/pcpu.m \
	src/macosx/qtmidi.m \
	src/macosx/quartz.m \
	src/macosx/qzfull.m \
	src/macosx/qzmouse.m \
	src/macosx/qzwindow.m \
	src/macosx/soundman.m \
	src/macosx/system.m \
	src/unix/ufile.c \
	src/unix/utimer.c \
	src/unix/uptimer.c \
	src/unix/usystem.c \
	src/unix/uthreads.c \
	src/misc/colconv.c

ALLEGRO_MODULE_VGA_FILES = \
	src/linux/lvga.c \
	src/misc/modex.c \
	src/misc/modexgfx.s \
	src/misc/vga.c

ALLEGRO_MODULE_SVGALIB_FILES = \
	src/linux/svgalib.c \
	src/linux/svgalibs.s

ALLEGRO_MODULE_FBCON_FILES = \
	src/linux/fbcon.c

ALLEGRO_MODULE_DGA2_FILES = \
	src/x/xdga2.c \
	src/x/xdga2s.s
	
ALLEGRO_MODULE_ALSADIGI_FILES = \
	src/unix/alsa5.c \
	src/unix/alsa9.c

ALLEGRO_MODULE_ALSAMIDI_FILES = \
	src/unix/alsamidi.c

ALLEGRO_MODULE_ESD_FILES = \
	src/unix/uesd.c

ALLEGRO_MODULE_ARTS_FILES = \
	src/unix/arts.c

ALLEGRO_MODULE_SGIAL_FILES = \
	src/unix/sgial.c

ALLEGRO_MODULE_JACK_FILES = \
	src/unix/jack.c

ALLEGRO_MAKEDOC_SOURCES = \
	docs/src/makedoc/makedoc.c \
	docs/src/makedoc/makehtml.c \
	docs/src/makedoc/makemisc.c \
	docs/src/makedoc/maketxt.c \
	docs/src/makedoc/makertf.c \
	docs/src/makedoc/maketexi.c \
	docs/src/makedoc/makeman.c \
	docs/src/makedoc/makechm.c \
	docs/src/makedoc/makedevh.c \
	docs/src/makedoc/makesci.c

ALLEGRO_DEMO_SOURCES = \
	demo/animsel.c \
	demo/bullet.c \
	demo/dirty.c \
	demo/expl.c \
	demo/star.c \
	demo/aster.c \
	demo/demo.c \
	demo/display.c \
	demo/game.c \
	demo/title.c

ALLEGRO_LIB_EXE_SOURCES = \
	setup/setup.c \
	tests/afinfo.c \
	tests/akaitest.c \
	tests/digitest.c \
	tests/filetest.c \
	tests/gfxinfo.c \
	tests/mathtest.c \
	tests/miditest.c \
	tests/play.c \
	tests/playfli.c \
	tests/test.c \
	tests/vesainfo.c \
	tools/colormap.c \
	tools/dat2c.c \
	tools/exedat.c \
	tools/pack.c \
	tools/rgbmap.c \
	tools/textconv.c

ALLEGRO_LIB_CPP_EXE_SOURCES = \
	tests/cpptest.cpp

ALLEGRO_LIB_X_EXE_SOURCES = \
	tools/x11/xkeymap.c \
	tools/x11/xf2pcx.c

ALLEGRO_LIB_EXES = \
	setup/setup \
	tests/afinfo \
	tests/akaitest \
	tests/digitest \
	tests/filetest \
	tests/gfxinfo \
	tests/mathtest \
	tests/miditest \
	tests/play \
	tests/playfli \
	tests/test \
	tests/vesainfo \
	tools/colormap \
	tools/dat2c \
	tools/exedat \
	tools/pack \
	tools/rgbmap \
	tools/textconv

ALLEGRO_LIB_CPP_EXES = \
	tests/cpptest

ALLEGRO_LIB_X_EXES = \
	tools/x11/xkeymap \
	tools/x11/xf2pcx

ALLEGRO_DATAFILE_EXE_SOURCES = \
	tools/dat.c \
	tools/dat2s.c \
	tools/grabber.c \
	tools/pat2dat.c

ALLEGRO_DATAFILE_EXES = \
	tools/dat \
	tools/dat2s \
	tools/grabber \
	tools/pat2dat

ALLEGRO_EXAMPLE_FILES = \
	examples/ex12bit.c \
	examples/ex3buf.c \
	examples/ex3d.c \
	examples/exaccel.c \
	examples/exalpha.c \
	examples/exbitmap.c \
	examples/exblend.c \
	examples/excamera.c \
	examples/excolmap.c \
	examples/exconfig.c \
	examples/excustom.c \
	examples/exdata.c \
	examples/exdbuf.c \
	examples/exexedat.c \
	examples/exfixed.c \
	examples/exflame.c \
	examples/exflip.c \
	examples/exfont.c \
	examples/exgui.c \
	examples/exhello.c \
	examples/exjoy.c \
	examples/exkeys.c \
	examples/exlights.c \
	examples/exmem.c \
	examples/exmidi.c \
	examples/exmouse.c \
	examples/expackf.c \
	examples/expal.c \
	examples/expat.c \
	examples/exquat.c \
	examples/exrgbhsv.c \
	examples/exsample.c \
	examples/exsyscur.c \
	examples/exscale.c \
	examples/exscn3d.c \
	examples/exscroll.c \
	examples/exshade.c \
	examples/exspline.c \
	examples/exsprite.c \
	examples/exstars.c \
	examples/exstream.c \
	examples/exswitch.c \
	examples/extimer.c \
	examples/extrans.c \
	examples/extruec.c \
	examples/exunicod.c \
	examples/exupdate.c \
	examples/exxfade.c \
	examples/exzbuf.c

ALLEGRO_EXAMPLE_EXES = \
	examples/ex12bit \
	examples/ex3buf \
	examples/ex3d \
	examples/exaccel \
	examples/exalpha \
	examples/exbitmap \
	examples/exblend \
	examples/excamera \
	examples/excolmap \
	examples/exconfig \
	examples/excustom \
	examples/exdata \
	examples/exdbuf \
	examples/exexedat \
	examples/exfixed \
	examples/exflame \
	examples/exflip \
	examples/exfont \
	examples/exgui \
	examples/exhello \
	examples/exjoy \
	examples/exkeys \
	examples/exlights \
	examples/exmem \
	examples/exmidi \
	examples/exmouse \
	examples/expackf \
	examples/expal \
	examples/expat \
	examples/exquat \
	examples/exrgbhsv \
	examples/exsample \
	examples/exsyscur \
	examples/exscale \
	examples/exscn3d \
	examples/exscroll \
	examples/exshade \
	examples/exspline \
	examples/exsprite \
	examples/exstars \
	examples/exstream \
	examples/exswitch \
	examples/extimer \
	examples/extrans \
	examples/extruec \
	examples/exunicod \
	examples/exupdate \
	examples/exxfade \
	examples/exzbuf

OBJ_CLEAN_FILES = \
	obj/*/*.o obj/*/*/*.o obj/*/*/*/*.o obj/*/*.obj obj/*/*/*.obj

OTHER_CLEAN_FILES = \
	obj/*/*.h obj/*/*.s obj/*/*.exe obj/*/*/*.lst obj/*/*/*.asm \
	obj/*/*.res obj/*/asmdef obj/*/*.inc \
	lib/*/*.a lib/unix/*.so* lib/unix/sta* \
	lib/*/*.lib lib/*/*.exp lib/*/*.dll \
	lib/*/*.pdb lib/*/*.ilk lib/*/*.map *.pdb */*.pdb \
	*/*.ilk */*.map */*.sym gmon.out */gmon.out */*.prf \
	allegro.log */allegro.log */*/allegro.log \
	log */log */*/log core */core */*/core

DISTCLEAN_FILES = \
	docs/texi/*.texi docs/texi/*.txi \
	docs/info/*.info docs/info/*.inf \
	docs/man/*.3 \
	docs/build/*.txt docs/txt/*.txt \
	docs/rtf/*.rtf \
	docs/html/*.html docs/html/*.htm docs/html/build/*.html \
	docs/html/build/*.htm docs/html/*.css \
	docs/chm/*.html docs/chm/build/*.html docs/chm/*.chm docs/chm/*.hh* \
	docs/devhelp/*.html docs/devhelp/build/*.html docs/devhelp/*.devhelp \
	docs/makedoc docs/allegro.dvi docs/allegro.ps* docs/allegro.pdf \
	docs/allegro.aux docs/allegro.cp docs/allegro.fn docs/allegro.fns \
	docs/allegro.ky docs/allegro.log docs/allegro.pg docs/allegro.toc \
	docs/allegro.tp docs/allegro.vr docs/scite/allegro.api \
	demo/demo \
	$(ALLEGRO_LIB_EXES) $(ALLEGRO_EXAMPLE_EXES) $(ALLEGRO_DATAFILE_EXES) \
	*.exe */*.exe */*/*.exe msvcmake.bat tests/win/*.scr \
	config.cache config.log config.status stamp-h stamp-h[0-9]* suid \
	makefile.dep makefile.info include/allegro/platform/alunixac.h allegro-config

VERYCLEAN_FILES = \
	authors AUTHORS changes CHANGES thanks THANKS readme.txt \
	obj/*/*/*.dep lib/*/*.def
