/*Automatically generated by mkalias.sh DO NOT EDIT!*/
#ifdef AGLX_VERSION_1_3
/*GLX1.3*/
#define glXGetFBConfigs __aglXGetFBConfigs
#define glXChooseFBConfig __aglXChooseFBConfig
#define glXGetFBConfigAttrib __aglXGetFBConfigAttrib
#define glXGetVisualFromFBConfig __aglXGetVisualFromFBConfig
#define glXCreateWindow __aglXCreateWindow
#define glXDestroyWindow __aglXDestroyWindow
#define glXCreatePixmap __aglXCreatePixmap
#define glXDestroyPixmap __aglXDestroyPixmap
#define glXCreatePbuffer __aglXCreatePbuffer
#define glXDestroyPbuffer __aglXDestroyPbuffer
#define glXQueryDrawable __aglXQueryDrawable
#define glXCreateNewContext __aglXCreateNewContext
#define glXMakeContextCurrent __aglXMakeContextCurrent
#define glXGetCurrentReadDrawable __aglXGetCurrentReadDrawable
#define glXGetCurrentDisplay __aglXGetCurrentDisplay
#define glXQueryContext __aglXQueryContext
#define glXSelectEvent __aglXSelectEvent
#define glXGetSelectedEvent __aglXGetSelectedEvent
#endif
#ifdef AGLX_VERSION_1_4
/*GLX1.4*/
#define glXGetProcAddress __aglXGetProcAddress
#endif

#ifdef AGLX_ARB_get_proc_address
/*GLX_ARB_get_proc_address*/
#define glXGetProcAddressARB __aglXGetProcAddressARB
#endif

#ifdef AGLX_SGI_swap_control
/*GLX_SGI_swap_control*/
#define glXSwapIntervalSGI __aglXSwapIntervalSGI
#endif

#ifdef AGLX_SGI_video_sync
/*GLX_SGI_video_sync*/
#define glXGetVideoSyncSGI __aglXGetVideoSyncSGI
#define glXWaitVideoSyncSGI __aglXWaitVideoSyncSGI
#endif

#ifdef AGLX_SGI_make_current_read
/*GLX_SGI_make_current_read*/
#define glXMakeCurrentReadSGI __aglXMakeCurrentReadSGI
#define glXGetCurrentReadDrawableSGI __aglXGetCurrentReadDrawableSGI
#endif

#ifdef AGLX_SGIX_video_source
/*GLX_SGIX_video_source*/
/*ThisoneneedsSGI'sheaderfile<dmedia/vl.h>tobeincludedfirst*/
#ifdef _VL_H_
#define glXCreateGLXVideoSourceSGIX __aglXCreateGLXVideoSourceSGIX
#define glXDestroyGLXVideoSourceSGIX __aglXDestroyGLXVideoSourceSGIX
#endif
#endif

#ifdef AGLX_EXT_import_context
/*GLX_EXT_import_context*/
#define glXGetCurrentDisplayEXT __aglXGetCurrentDisplayEXT
#define glXQueryContextInfoEXT __aglXQueryContextInfoEXT
#define glXGetContextIDEXT __aglXGetContextIDEXT
#define glXImportContextEXT __aglXImportContextEXT
#define glXFreeContextEXT __aglXFreeContextEXT
#endif

#ifdef AGLX_SGIX_fbconfig
/*GLX_SGIX_fbconfig*/
#define glXGetFBConfigAttribSGIX __aglXGetFBConfigAttribSGIX
#define glXChooseFBConfigSGIX __aglXChooseFBConfigSGIX
#define glXCreateGLXPixmapWithConfigSGIX __aglXCreateGLXPixmapWithConfigSGIX
#define glXCreateContextWithConfigSGIX __aglXCreateContextWithConfigSGIX
#define glXGetVisualFromFBConfigSGIX __aglXGetVisualFromFBConfigSGIX
#define glXGetFBConfigFromVisualSGIX __aglXGetFBConfigFromVisualSGIX
#endif

#ifdef AGLX_SGIX_pbuffer
/*GLX_SGIX_pbuffer*/
#define glXCreateGLXPbufferSGIX __aglXCreateGLXPbufferSGIX
#define glXDestroyGLXPbufferSGIX __aglXDestroyGLXPbufferSGIX
#define glXQueryGLXPbufferSGIX __aglXQueryGLXPbufferSGIX
#define glXSelectEventSGIX __aglXSelectEventSGIX
#define glXGetSelectedEventSGIX __aglXGetSelectedEventSGIX
#endif

#ifdef AGLX_SGI_cushion
/*GLX_SGI_cushion*/
#define glXCushionSGI __aglXCushionSGI
#endif

#ifdef AGLX_SGIX_video_resize
/*GLX_SGIX_video_resize*/
#define glXBindChannelToWindowSGIX __aglXBindChannelToWindowSGIX
#define glXChannelRectSGIX __aglXChannelRectSGIX
#define glXQueryChannelRectSGIX __aglXQueryChannelRectSGIX
#define glXQueryChannelDeltasSGIX __aglXQueryChannelDeltasSGIX
#define glXChannelRectSyncSGIX __aglXChannelRectSyncSGIX
#endif

#ifdef AGLX_SGIX_dmbuffer
/*GLX_SGIX_dmbuffer*/
/*ThisoneneedsSGI'sheaderfile<dmedia/dm_buffer.h>tobeincludedfirst*/
#ifdef _DM_BUFFER_H_
#define glXAssociateDMPbufferSGIX __aglXAssociateDMPbufferSGIX
#endif
#endif

#ifdef AGLX_SGIX_swap_group
/*GLX_SGIX_swap_group*/
#define glXJoinSwapGroupSGIX __aglXJoinSwapGroupSGIX
#endif

#ifdef AGLX_SGIX_swap_barrier
/*GLX_SGIX_swap_barrier*/
#define glXBindSwapBarrierSGIX __aglXBindSwapBarrierSGIX
#define glXQueryMaxSwapBarriersSGIX __aglXQueryMaxSwapBarriersSGIX
#endif

#ifdef AGLX_SUN_get_transparent_index
/*GLX_SUN_get_transparent_index*/
#define glXGetTransparentIndexSUN __aglXGetTransparentIndexSUN
#endif

#ifdef AGLX_MESA_copy_sub_buffer
/*GLX_MESA_copy_sub_buffer*/
#define glXCopySubBufferMESA __aglXCopySubBufferMESA
#endif

#ifdef AGLX_MESA_pixmap_colormap
/*GLX_MESA_pixmap_colormap*/
#define glXCreateGLXPixmapMESA __aglXCreateGLXPixmapMESA
#endif

#ifdef AGLX_MESA_release_buffers
/*GLX_MESA_release_buffers*/
#define glXReleaseBuffersMESA __aglXReleaseBuffersMESA
#endif

#ifdef AGLX_MESA_set_3dfx_mode
/*GLX_MESA_set_3dfx_mode*/
#define glXSet3DfxModeMESA __aglXSet3DfxModeMESA
#endif

#ifdef AGLX_OML_sync_control
/*GLX_OML_sync_control*/
#define glXGetSyncValuesOML __aglXGetSyncValuesOML
#define glXGetMscRateOML __aglXGetMscRateOML
#define glXSwapBuffersMscOML __aglXSwapBuffersMscOML
#define glXWaitForMscOML __aglXWaitForMscOML
#define glXWaitForSbcOML __aglXWaitForSbcOML
#endif


#ifdef AGLX_SGIX_hyperpipe
#define glXQueryHyperpipeNetworkSGIX __aglXQueryHyperpipeNetworkSGIX
#define glXHyperpipeConfigSGIX __aglXHyperpipeConfigSGIX
#define glXQueryHyperpipeConfigSGIX __aglXQueryHyperpipeConfigSGIX
#define glXDestroyHyperpipeConfigSGIX __aglXDestroyHyperpipeConfigSGIX
#define glXBindHyperpipeSGIX __aglXBindHyperpipeSGIX
#define glXQueryHyperpipeBestAttribSGIX __aglXQueryHyperpipeBestAttribSGIX
#define glXHyperpipeAttribSGIX __aglXHyperpipeAttribSGIX
#define glXQueryHyperpipeAttribSGIX __aglXQueryHyperpipeAttribSGIX
#endif


#ifdef AGLX_MESA_agp_offset
#define glXGetAGPOffsetMESA __aglXGetAGPOffsetMESA
#endif


#ifdef AGLX_EXT_texture_from_pixmap
#define glXBindTexImageEXT __aglXBindTexImageEXT
#define glXReleaseTextImageEXT __aglXReleaseTextImageEXT
#endif

#ifdef AGLX_NV_video_out
#define glXGetVideoDeviceNV __aglXGetVideoDeviceNV
#define glXReleaseVideoDeviceNV __aglXReleaseVideoDeviceNV
#define glXBindVideoImageNV __aglXBindVideoImageNV
#define glXReleaseVideoImageNV __aglXReleaseVideoImageNV
#define glXSendPbufferToVideoNV __aglXSendPbufferToVideoNV
#define glXGetVideoInfoNV __aglXGetVideoInfoNV
#endif

#ifdef AGLX_NV_swap_group
#define glXJoinSwapGroupNV __aglXJoinSwapGroupNV
#define glXBindSwapBarrierNV __aglXBindSwapBarrierNV
#define glXQuerySwapGroupNV __aglXQuerySwapGroupNV
#define glXQueryMaxSwapGroupsNV __aglXQueryMaxSwapGroupsNV
#define glXQueryFrameCountNV __aglXQueryFrameCountNV
#define glXResetFrameCountNV __aglXResetFrameCountNV
#endif
