#cmakedefine ALLEGRO_CFG_ACODEC_FLAC
#cmakedefine ALLEGRO_CFG_ACODEC_MODAUDIO
#cmakedefine ALLEGRO_CFG_ACODEC_VORBIS
#cmakedefine ALLEGRO_CFG_ACODEC_TREMOR
#cmakedefine ALLEGRO_CFG_ACODEC_CREATIVE_VOICE


/* Define if the library should be loaded dynamically. */
#cmakedefine ALLEGRO_CFG_ACODEC_FLAC_DLL "@ALLEGRO_CFG_ACODEC_FLAC_DLL@"
#cmakedefine ALLEGRO_CFG_ACODEC_DUMB_DLL "@ALLEGRO_CFG_ACODEC_DUMB_DLL@"
#cmakedefine ALLEGRO_CFG_ACODEC_VORBISFILE_DLL "@ALLEGRO_CFG_ACODEC_VORBISFILE_DLL@"
#cmakedefine ALLEGRO_CFG_ACODEC_CREATIVE_VOICE_DLL "@ALLEGRO_CFG_ACODEC_CREATIVE_VOICE_DLL@"
