#cmakedefine A5O_CFG_ACODEC_FLAC
#cmakedefine A5O_CFG_ACODEC_DUMB
#cmakedefine A5O_CFG_ACODEC_OPENMPT
#cmakedefine A5O_CFG_ACODEC_VORBIS
#cmakedefine A5O_CFG_ACODEC_TREMOR
#cmakedefine A5O_CFG_ACODEC_OPUS
#cmakedefine A5O_CFG_ACODEC_MP3


/* Define if the library should be loaded dynamically. */
#cmakedefine A5O_CFG_ACODEC_FLAC_DLL "@A5O_CFG_ACODEC_FLAC_DLL@"
#cmakedefine A5O_CFG_ACODEC_DUMB_DLL "@A5O_CFG_ACODEC_DUMB_DLL@"
#cmakedefine A5O_CFG_ACODEC_VORBISFILE_DLL "@A5O_CFG_ACODEC_VORBISFILE_DLL@"
#cmakedefine A5O_CFG_ACODEC_OPUSFILE_DLL "@A5O_CFG_ACODEC_OPUSFILE_DLL@"
