.PRECIOUS: %.o

CC = gcc
CFLAGS = -Wall -O2 -g -Wno-deprecated-declarations -Wno-unused
INCLUDE = -Iinclude

ifdef CPU
   CFLAGS += -mcpu=$(CPU)
else
   CFLAGS += -mcpu=i686
endif

LIBS = -lalleg -lm
OBJDIR = obj/djgpp/
LIBDIR = lib/djgpp/
EXEDIR = bin/djgpp/

EXESUFFIX = .exe
EXEPREFIX =

