Import( 'context' )
import addons

configs = []

configs.extend(['openal-config --libs'])
configs.extend(['pkg-config --libs alsa'])

addons.do_build(
    context = context,
    source = Split("""
        alsa.c
        audio.c
        openal.c
    """),
    dir = 'audio',
    name = 'audio',
    install_headers = ['allegro5/audio.h','allegro5/internal/aintern_audio.h'],
    configs = configs
)
