#----------------------------------#
#--- Source file list -------------#

C_SOURCE = alleggl.c glvtable.c scorer.c math.c aglf.c fontconv.c texture.c glext.c gui.c videovtb.c
WIN_SOURCE = win.c
DOS_SOURCE = djgpp.c
MACOSX_SOURCE = macosx.m

C_DEPEND = alleggl.h allglint.h allegrogl/gl_ext.h allegrogl/gl_header_detect.h

EXAMP_SOURCE = test.c tex.c dumbtest.c dialog.c extext.c extextur.c exmasked.c \
    exalleg.c exalpfnt.c excamera.c exgui.c exext.c exmipmaps.c fonttest.c exblend.c

HEADERS = include/alleggl.h include/allegrogl/gl_ext.h include/allegrogl/gl_header_detect.h
EXT_HEADERS_PATH = include/allegrogl/GLext
EXT_HEADERS = $(EXT_HEADERS_PATH)/gl_ext_defs.h $(EXT_HEADERS_PATH)/gl_ext_api.h $(EXT_HEADERS_PATH)/gl_ext_list.h $(EXT_HEADERS_PATH)/gl_ext_alias.h

default: all
all: examples lib
	@echo -
	@echo Success!


#----------------------------------#
#-- Set up names and dependencies -#


SRC_DIR = src
LIB_DIR = lib/$(COMPILER)
ALLEG_LIB_DIR = ../../lib/$(COMPILER)
EXAMPLE_DIR = examp
INCLUDE_DIR = include include/allegrogl include/allegrogl/GLext ../../include

# Release mode is default
OBJ_DIR_BASE = obj/$(COMPILER)/release
LIB_NAME_BASE = agl
LINK_LIB_BASE = alleg

ifdef DEBUGMODE
  OBJ_DIR_BASE = obj/$(COMPILER)/debug
  LIB_NAME_BASE = agld
  LINK_LIB_BASE = alld
endif

ifdef PROFILEMODE
# Profiling build of AllegroGL is currnetly not supported
# OBJ_DIR_BASE = obj/$(COMPILER)/profile
#  LIB_NAME_BASE = aglp
  LINK_LIB_BASE = allp
endif

ifdef STATICLINK
  STATICALLEGRO=1
  STATIC_SUFFIX = _s
else
  STATIC_SUFFIX =
endif

ifdef STATICRUNTIME
  CRT_SUFFIX = _crt
else
  CRT_SUFFIX =
endif

ifdef ALLEGRO_USE_C
  NO_ASM_SUFFIX = _c
else
  NO_ASM_SUFFIX =
endif

SUFFIX = $(addsuffix $(NO_ASM_SUFFIX), $(addsuffix $(CRT_SUFFIX), $(STATIC_SUFFIX)))

OBJ_DIR = $(addsuffix $(SUFFIX), $(OBJ_DIR_BASE))
LIB_NAME = $(addsuffix $(SUFFIX), $(LIB_NAME_BASE))
LINK_LIB = $(addsuffix $(SUFFIX), $(LINK_LIB_BASE))

