Import( 'context' )
import addons
import helpers

def getOption(name, default = 0):
    return context.getLibraryEnv()[name]

opts = Options('options-unix.py', ARGUMENTS)
opts.Add('flac', 'Enable FLAC', 1)
opts.Add('sndfile', 'Enable sndfile', 1)
opts.Add('ogg', 'Enable ogg', 1)
opts.Update(context.getLibraryEnv())
opts.Save('options-addons-acodec.py',context.getLibraryEnv())
Help(opts.GenerateHelpText(context.getLibraryEnv()))

settings = helpers.SimpleHash()
settings["ALLEGRO_CFG_ACODEC_OGG"] = getOption('ogg', False)
settings["ALLEGRO_CFG_ACODEC_FLAC"] = getOption('flac', False)
settings["ALLEGRO_CFG_ACODEC_SNDFILE"] = getOption('sndfile', False)

helpers.parse_cmake_h(context.getLibraryEnv(),settings,'#addons/acodec/allegro5/internal/aintern_acodec.h.cmake','#addons/acodec/allegro5/internal/aintern_acodec.h')

addons.do_build(
    context = context,
    source = Split("""
       acodec.c
       ex_acodec.c
       flac.c
       ogg.c
       wav.c
    """),
    dir = 'acodec',
    name = 'acodec',
    install_headers = ['allegro5/acodec.h'],
    includes = ['#addons/audio']
)
