Import( 'context' )
import addons

addons.do_build(
    context = context,
    source = Split("""
       acodec.c
       ex.c
       flac.c
       ogg.c
       wav.c
    """),
    dir = 'acodec',
    name = 'acodec',
    install_headers = ['allegro5/acodec.h']
)
