#!/bin/sh -e
# Generate an fragment to be inserted at the bottom of HTML pages.
# The timestamp follows RFC 3339.
# We use UTC.

cat << EOF > $1
<p>
Last updated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
</p>
EOF
