#!/bin/sh
#
# SYNOPSIS
#
# make_html_refs --output OUTPUT-FILE DOC-FILE...
#
# DESCRIPTION
#
# Generate a file containing (HTML-specific) link definitions for each API
# entry found.  e.g. if foo.txt contains "# API: bar" then we generate:
#
#   [bar]: foo.html#bar
#

set -e

# Speed up grep and sed.
export LC_ALL=C

make_html_refs() {
    file=$1
    base=${file##*/}
    base=${base%.*}     # remove any extension
    grep -e '^#\+ API: ' "$file" |
    sed -e 's|^#\+ API: \(.*\)|[\1]: '${base}'.html#\1|'
}

case $1 in
    -o|--output)
        OUTPUT=$2
        shift 2
        ;;
    *)
        echo "make_html_refs: Missing output file." 1>&2
        exit 1
        ;;
esac

for file; do
    make_html_refs "$file"
done > "$OUTPUT"

# vim: set et:
