#!/bin/sh
#
# SYNOPSIS
#
# make_protos --output OUTPUT-FILE SOURCE-FILE...
#
# DESCRIPTION
#
# Extract all the function prototypes and type/enum declarations which have
# Natural Docs tags Function: Type: Enum:
#

set -e

export LC_CTYPE=C

case $1 in
    --output)
        PROTOS=$2
        shift 2
        ;;
    *)
        echo "make_protos: Missing --output options." 1>&2
        exit 1
        ;;
esac

exec awk -f $0.awk "$@" > "$PROTOS"

# vim: set et:
