#!/bin/sh -e
#
# SYNOPSIS
#
# make_protos SOURCE-FILE...
#
# DESCRIPTION
#
# Extract all the function prototypes and type/enum declarations which have
# Natural Docs tags Function: Type: Enum:
#

# Speed up awk.
export LC_CTYPE=C

exec awk -f "$0.awk" "$@"

# vim: set et:
