#!/bin/sh
#
# SYNOPSIS
#
# split_api_docs OUTPUT-DIR < DOC-FILE...
#
# DESCRIPTION
#
# Read documentation from standard input.  Dump the bodies of API entries
# into separate files in OUTPUT-DIR.
#
# (For portability, stick to POSIX shell constructs in this script.)
#

set -e

rawecho() {
cat <<EOF
$1
EOF
}

if test -z "$1"
then
    echo "Usage: split_api_docs OUTPUT-DIR"
    exit 1
fi
OUTPUT_DIR=$1
test -d "$OUTPUT_DIR" || mkdir "$OUTPUT_DIR"

exec > /dev/null

IFS=
while read -r line
do
    case $line in
        *"# API: "*)
            name=${line#*API: }
            exec > "$OUTPUT_DIR/$name"
            ;;
        "#"*)
            exec > /dev/null
            ;;
        -*)
            rawecho "$line"
            ;;
        *)
            echo "$line"
            ;;
    esac
done

# vim: set et:
