// cmake doesn't work for iphone (yet?), unfortunately, so have to construct
// this manually for now

#define ALLEGRO_CFG_OPENGL
#define ALLEGRO_IPHONE
#define ALLEGRO_NO_ASM
#define RETSIGTYPE void
#define ALLEGRO_HAVE_DIRENT_H
#define ALLEGRO_HAVE_INTTYPES_H
#define ALLEGRO_HAVE_STDBOOL_H
#define ALLEGRO_HAVE_STDINT_H
#define ALLEGRO_HAVE_SYS_STAT_H
#define ALLEGRO_HAVE_SYS_TIME_H
#define ALLEGRO_HAVE_TIME_H
#define ALLEGRO_HAVE_SYS_UTSNAME_H
#define ALLEGRO_HAVE_SYS_TYPES_H
#define ALLEGRO_HAVE_OSATOMIC_H
#define ALLEGRO_HAVE_MKSTEMP
#define ALLEGRO_HAVE_MMAP
#define ALLEGRO_HAVE_MPROTECT
#define ALLEGRO_HAVE_SCHED_YIELD
#define ALLEGRO_HAVE_SYSCONF
#define ALLEGRO_HAVE_FSEEKO
#define ALLEGRO_HAVE_FTELLO
#define ALLEGRO_HAVE_VA_COPY
#define ALLEGRO_LITTLE_ENDIAN
#define ALLEGRO_USE_CONSTRUCTOR
#define ALLEGRO_CFG_PTHREADS_TLS

