#ifndef ALLEGRO_INTERNAL_COLOR_H
#define ALLEGRO_INTERNAL_COLOR_H

typedef struct ALLEGRO_INDEPENDANT_COLOR ALLEGRO_INDEPENDANT_COLOR;

struct ALLEGRO_INDEPENDANT_COLOR
{
   float r, g, b, a;
};

#endif
