@echo off

if [%1] == []        goto help
if [%1] == [djgpp]   goto djgpp
if [%1] == [mingw]   goto mingw
if [%1] == [mingw32] goto mingw
if [%1] == [msvc]    goto msvc6
if [%1] == [msvc6]   goto msvc6
if [%1] == [msvc7]   goto msvc7
if [%1] == [msvc8]   goto msvc8
if [%1] == [msvc9]   goto msvc9

:nosup
echo Platform not supported by loadpng.
goto end

:help
echo.
echo Usage: fix platform
echo.
echo Where platform is one of:
echo     djgpp, mingw32, msvc6, msvc7, msvc8, msvc9
echo.
goto end

:djgpp
echo Configuring loadpng for DOS/djgpp...
echo #generated by fix.bat        > Makefile
echo MAKEFILE_INC=Makefile.dj    >> Makefile
echo include Makefile.all        >> Makefile
goto end

:mingw
echo Configuring loadpng for Windows/MinGW...
echo #generated by fix.bat        > Makefile
echo MAKEFILE_INC=Makefile.mgw   >> Makefile
echo include Makefile.all        >> Makefile
goto end

:msvc6
echo Configuring loadpng for Windows/MSVC6...
echo #generated by fix.bat         > Makefile
echo COMPILER_MSVC6 = 1           >> Makefile
echo include Makefile.vc          >> Makefile
goto end

:msvc7
echo Configuring loadpng for Windows/MSVC7...
echo #generated by fix.bat         > Makefile
echo COMPILER_MSVC7 = 1           >> Makefile
echo include Makefile.vc          >> Makefile
goto end

:msvc8
echo Configuring loadpng for Windows/MSVC8...
echo #generated by fix.bat         > Makefile
echo COMPILER_MSVC8 = 1           >> Makefile
echo include Makefile.vc          >> Makefile
goto end

:msvc9
echo Configuring loadpng for Windows/MSVC9...
echo #generated by fix.bat         > Makefile
rem MSVC9 uses MSVC8 settings
echo COMPILER_MSVC8 = 1           >> Makefile
echo include Makefile.vc          >> Makefile
goto end

:end

