@echo off

if [%1] == []        goto help
if [%1] == [djgpp]   goto djgpp
if [%1] == [mingw]   goto mingw
if [%1] == [mingw32] goto mingw

:nosup
echo Platform not supported by loadpng.
goto end

:help
echo.
echo Usage: fix platform
echo.
echo Where platform is one of:
echo     djgpp, mingw32
echo.
goto end

:djgpp
echo Configuring loadpng for DOS/djgpp...
echo #generated by fix.bat        > Makefile
echo MAKEFILE_INC=Makefile.dj    >> Makefile
echo include Makefile.all        >> Makefile
goto end

:mingw
echo Configuring loadpng for Windows/MinGW...
echo #generated by fix.bat        > Makefile
echo MAKEFILE_INC=Makefile.mgw   >> Makefile
echo include Makefile.all        >> Makefile
goto end

:end

