/*#define ALLEGRO_CFG_ACODEC_FLAC*/
/*#define ALLEGRO_CFG_ACODEC_MODAUDIO*/
/*#define ALLEGRO_CFG_ACODEC_VORBIS*/

/* Define if the library should be loaded dynamically. */
/*#define ALLEGRO_CFG_ACODEC_FLAC_DLL "@ALLEGRO_CFG_ACODEC_FLAC_DLL@"*/
/*#define ALLEGRO_CFG_ACODEC_DUMB_DLL "@ALLEGRO_CFG_ACODEC_DUMB_DLL@"*/
/*#define ALLEGRO_CFG_ACODEC_VORBISFILE_DLL "@ALLEGRO_CFG_ACODEC_VORBISFILE_DLL@"*/
